# Site settings
title: Lorem Ipsum - Web Developer
description: "A blog about lorem ipsum ..."
baseurl: "/space-jekyll-template" # for test: remove string '/space-jekyll-template' to ''
url: https://minji1208.github.io/

# User settings
사용자 이름 :민지
user_title : Lorem Ipsum- 프런트 엔드
email: lorem.lorem@ipsum.com
twitter_username: loremipsum
github_username:  minji
gplus_username:  loremipsum
linkedin_public_url: loremipsum # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
disqus_username: loremipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false


# projects in header index
projects:
  - name: fluany
    url: https://github.com/fluany/fluany
  - name: vim-frontend
    url: https://github.com/victorvoid/vim-frontend
  - name: generator-capybara
    url: https://github.com/victorvoid/generator-capybara 

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']

theme: jekyll-theme-minimal
